language: node_js

node_js:
  - "0.12"
  - "0.10"

before_script:
  # Starting virtual framebuffer for running browsers
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  email: false
